pipeline {
    agent any
    stages {
        stage("build") {
            steps{
                sh "mvn clean install"
            }
        }
        stage("Infra_provisioning") {
            steps{
                sh "terraform init"
                sh "terraform plan"
                sh "terraform apply -auto-approve"
            }
        }
        stage("post_build") {
            steps{
                
                sh 'sshpass -p "jen@1234" scp /var/lib/jenkins/workspace/first-pipeline-for-terraform/webapp/target/webapp.war  terraform@$(terraform output -json instance_ips | jq -r \'.[0]\'):/home/terraform/webapp.war'
                sh 'ssh terraform@$(terraform output -json instance_ips | jq -r \'.[0]\') "sh -x /opt/apache-tomcat-8.5.35/bin/shutdown.sh"'
                sh 'ssh terraform@$(terraform output -json instance_ips | jq -r \'.[0]\') "sh -x /opt/apache-tomcat-8.5.35/bin/shutdown.sh"'
            }
        }
    }
}
