pipeline {
    agent any
     tools {
	maven 'Maven'
     }
    stages {
	stage("Sonarcloud_analysis") {
	    steps {
                        sh 'mvn clean package'
                }
            }
	    }
        stage("Infra_provisioning") {
            steps{
                sh "terraform init"
                sh "terraform plan"
                sh "terraform apply -auto-approve"
            }
        }
        stage("post_build") {
            steps{
                
                sh 'sshpass -p "jen@1234" ssh -o \'StrictHostKeyChecking no\' terraform@$(terraform output -json instance_ips | jq -r \'.[0]\')'
                sh 'sshpass -p "jen@1234" scp /var/lib/jenkins/workspace/first-pipeline-for-terraform/webapp/target/webapp.war  terraform@$(terraform output -json instance_ips | jq -r \'.[0]\'):/home/terraform/webapp.war'
                sh 'sshpass -p "jen@1234" ssh terraform@$(terraform output -json instance_ips | jq -r \'.[0]\') "sudo mv /home/terraform/webapp.war /opt/apache-tomcat-8.5.35/webapps"'
                sh 'sshpass -p "jen@1234" ssh terraform@$(terraform output -json instance_ips | jq -r \'.[0]\') "sudo sh -x /opt/apache-tomcat-8.5.35/bin/shutdown.sh"'
                sh 'sshpass -p "jen@1234" ssh terraform@$(terraform output -json instance_ips | jq -r \'.[0]\') "sudo sh -x /opt/apache-tomcat-8.5.35/bin/startup.sh"'
            }
        }
    
 }
