pipeline {
    agent any
    stages {
        stage("pre_build") {
            steps{
                mvn clean install
            }
        }
        stage("build") {
            steps{
                echo 'Building maven packages'
                echo 'Creating docker images using war file'
            }
        }
        stage("post_build") {
            steps{
                echo 'Running terraform commands'
                echo 'Deploy docker images to target server'
            }
        }
    }
}
